"""initial schema

Revision ID: 0d24ea3d5879
Revises: 
Create Date: 2026-03-19 17:18:44.830963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d24ea3d5879'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fraud_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('upi_id', sa.String(), nullable=False),
    sa.Column('fraud_type', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('utr_number', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('evidence_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fraud_reports_upi_id'), 'fraud_reports', ['upi_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('upi_id', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('is_fraud', sa.Boolean(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('post_call_flag', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_upi_id'), 'transactions', ['upi_id'], unique=False)
    op.create_table('upi_profiles',
    sa.Column('upi_id', sa.String(), nullable=False),
    sa.Column('registration_date', sa.DateTime(), nullable=False),
    sa.Column('transaction_count', sa.Integer(), nullable=False),
    sa.Column('fraud_count', sa.Integer(), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('blacklisted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('upi_id')
    )
    op.create_index(op.f('ix_upi_profiles_upi_id'), 'upi_profiles', ['upi_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_upi_profiles_upi_id'), table_name='upi_profiles')
    op.drop_table('upi_profiles')
    op.drop_index(op.f('ix_transactions_upi_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_fraud_reports_upi_id'), table_name='fraud_reports')
    op.drop_table('fraud_reports')
    # ### end Alembic commands ###
