"""add_m2_upi_profile_columns

Revision ID: 1445fc28da35
Revises: 0d24ea3d5879
Create Date: 2026-04-09 01:19:16.475893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1445fc28da35'
down_revision: Union[str, Sequence[str], None] = '0d24ea3d5879'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upi_profiles', sa.Column('account_age_days', sa.Integer(), nullable=True))
    op.add_column('upi_profiles', sa.Column('total_tx_volume', sa.Float(), nullable=True))
    op.add_column('upi_profiles', sa.Column('unique_senders', sa.Integer(), nullable=True))
    op.add_column('upi_profiles', sa.Column('name_handle_similarity', sa.Float(), nullable=True))
    op.add_column('upi_profiles', sa.Column('avg_tx_amount', sa.Float(), nullable=True))
    op.add_column('upi_profiles', sa.Column('tx_count_last_7d', sa.Integer(), nullable=True))
    op.add_column('upi_profiles', sa.Column('tx_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('upi_profiles', 'tx_count')
    op.drop_column('upi_profiles', 'tx_count_last_7d')
    op.drop_column('upi_profiles', 'avg_tx_amount')
    op.drop_column('upi_profiles', 'name_handle_similarity')
    op.drop_column('upi_profiles', 'unique_senders')
    op.drop_column('upi_profiles', 'total_tx_volume')
    op.drop_column('upi_profiles', 'account_age_days')
    # ### end Alembic commands ###
